coverage_server:
  ros__parameters:
    use_sim_time: True
    default_headland_width: 0.20
    robot_width: 0.6
    operation_width: 0.6
    min_turning_radius: 0.0
    linear_curv_change: 1000000.0
    coordinates_in_cartesian_frame: true
    default_allow_overlap: false
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 4.7124 # We know its aligned for the demo

coverage_task:
  ros__parameters:
    use_sim_time: True
    frequency: 10.0
